# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sound & Fury
real_name: Andrew Bell
domain: evoludo.com
email: andrew@evoludo.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about audio, programming, music, and oddly
  named cats.
baseurl: / # the subpath of your site, e.g. /blog
url: "https://www.evoludo.com" # the base hostname & protocol for your site
github_username:  evoludo

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#permalink:        pretty
permalink:        /:slug/

# Setup
tagline:          'a blog by Andrew Bell'

author:
  name:           'Andrew Bell'
  url:            https://www.evoludo.com

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/evoludo
linkedin:         https://www.linkedin.com/in/evoludo

gems:
    - jekyll-sitemap

exclude:
    - "Gemfile"
    - "Gemfile.*"
    - "CNAME"
    - "*.sh"
